### ISSUE TITLE
list project command failing

### ISSUE THREAD

**Issue by vivekaltruist** [spacewander/GSoC#1]
I am getting following error on running command: **GSoC 2014**

{ [Error: ENOENT, open '/Users/labuser/Documents/work/GSoC-master/GSoCProjects.json']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/labuser/Documents/work/GSoC-master/GSoCProjects.json' }
undefined:1
undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /usr/local/lib/node_modules/gsoc/lib/store.js:16:20
    at fs.js:263:20
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by raincrash** [comment]
Correct me if I'm wrong here, the parser uses resources from https://www.google-melange.com/gsoc/ . The program has been moved from melange this year.

**Comment by spacewander** [comment]
There is no API to get historical GSoC project data any more, so I have to announce that this project is abandoned.

However, with https://summerofcode.withgoogle.com/api/program/current/organization/ you can get the project data of this year. It may be helpful.
